import { QdrantClient } from '@qdrant/js-client-rest';

import dotenv from 'dotenv';

dotenv.config(
    { path: "../.env" }
);

const qdrantClient = new QdrantClient({
    url: process.env.QUADRANT_CLUSTER_ENDPOINT,
    apiKey: process.env.QUADRANT_API_KEY,
});

//INITIzize framework collection

const initFrameworkCollection = async () => {
    const collectionName = "frameworks"

    try {
        const res = await qdrantClient.getCollections();
        const exists = res.collections.some(c => c.name === collectionName);

        if (!exists) {
            await qdrantClient.createCollection(collectionName, {
                vectors: {
                    size: 384,// vector size generated by oure hugging face 
                    distance: "Cosine", // standarad distance metric for 
                },
            });

            await qdrantClient.createPayloadIndex(collectionName, {
                field_name: "frameworkId",
                field_schema: "keyword",
            });
            console.log(` Qdrant Collection '${collectionName}' created successfully.`);
        } else {
            console.log(`ℹ Qdrant Collection '${collectionName}' already exists.`);
        }
    } catch (err) {
        console.error(` Error setting up Qdrant Collection '${collectionName}':`, err);
    }
};







//Test connection and initilize
try {
    const res = await qdrantClient.getCollections();
    console.log("Qdrant database connected", res.collections.length, "collection found")

    await initFrameworkCollection();

     try {
        await qdrantClient.createPayloadIndex("frameworks", {
            field_name: "frameworkId",
            field_schema: "keyword",
        });

        console.log(" frameworkId index created");
    } catch (err) {
        console.log(" index creation failed", err);
    }

} catch (err) {
    console.log("Qdrant Database connection Error", err);
}

export default qdrantClient;